-- CreateEnum
CREATE TYPE "ArtistType" AS ENUM ('VISIONARY', 'CONSUMMATE_PROFESSIONAL', 'ANALYZER', 'TECH_ARTIST', 'ENTERTAINER', 'MAVERICK', 'DREAMER', 'FEELER', 'TORTURED', 'SOLO');

-- CreateEnum
CREATE TYPE "CreativeWorkType" AS ENUM ('ENTREPRENEUR', 'TEAM_PLAYER', 'CONNECTOR_ORGANIZER', 'FINISHER', 'ENTHUSIASTIC_FACILITATOR', 'CREATIVE_INITIATOR', 'COLLABORATOR');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "achievements" JSONB DEFAULT '[]',
ADD COLUMN     "artistType" "ArtistType",
ADD COLUMN     "bio" TEXT,
ADD COLUMN     "featuredWorks" JSONB DEFAULT '[]',
ADD COLUMN     "skills" TEXT[],
ADD COLUMN     "socialLinks" JSONB DEFAULT '{}',
ADD COLUMN     "workType" "CreativeWorkType";
