import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/styles/globals.css"
import Providers from "./Providers"
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} overflow-visible`}>
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  )
}
